version: '3'

volumes:
  static:
  database:
  logs:
  media:

services:

  mysql:
    image: mysql
    container_name: nbutacm_mysql
    hostname: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=nbutacm_mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=iillIILL!!11iill
      - MYSQL_ROOT_PASSWORD=iillIILL!!11iill

  redis:
    image: redis
    container_name: nbutacm_redis
    command: redis-server --requirepass szdfhjklhasjklfe
    ports:
      - "6379:6379"

  nbutacm:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: nbutacm
    container_name: nbutacm
    working_dir: /app
    volumes:
      - ./database:/app/database
      - ./static:/app/static
      - ./media:/app/media
    #env_files:
    #  - .envs/.production
    ports:
      - "8000:8000"
    command: /start.sh

#  nbutacm_nginx:
#    build:
#      context: .
#      dockerfile: compose/production/nginx/Dockerfile
#    image: nbutacm_nginx
#    container_name: nbutacm_nginx
#    volumes:
#      - ./static:/apps/nbutacm/static
#      - ./logs/nginx:/var/log/nginx
#      - ./media:/apps/nbutacm/media
#    ports:
#      - "80:80"
  nbutacm_my_nginx:
    build:
      context: .
      dockerfile: compose/production/my_nginx/Dockerfile
    image: nbutacm_my_nginx
    container_name: nbutacm_my_nginx
    volumes:
      - ./static:/apps/nbutacm/static
      - ./media:/apps/nbutacm/media
      - .logs/nginx:/usr/local/nginx/logs
    ports:
      - "80:80"
