# Generated by Django 2.2.3 on 2021-02-15 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_membergrade_memberinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_url', models.CharField(max_length=200, verbose_name='略缩图地址')),
                ('activity_time', models.CharField(max_length=200, verbose_name='活动时间')),
                ('activity_name', models.CharField(max_length=200, verbose_name='活动名称')),
                ('activity_note', models.CharField(max_length=300, verbose_name='活动记录')),
                ('created_time', models.DateTimeField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '活动记录',
                'verbose_name_plural': '活动记录',
            },
        ),
        migrations.CreateModel(
            name='ActivityGalleryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(max_length=200, verbose_name='图片地址')),
                ('activity_gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ActivityGallery')),
            ],
            options={
                'verbose_name': '活动记录的照片',
                'verbose_name_plural': '活动记录的照片',
            },
        ),
    ]
