# Generated by Django 2.2.3 on 2021-02-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_configinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configinfo',
            name='index_photo_url',
            field=models.CharField(default='https://ultronxross.xyz/cdn/img/nbutacm/header-bg.jpg', max_length=200, verbose_name='主页图片地址'),
        ),
    ]
