# Generated by Django 2.2.3 on 2021-02-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210218_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='url',
            field=models.CharField(default='#', max_length=70, verbose_name='博客链接'),
        ),
    ]
