# Generated by Django 2.2.3 on 2021-02-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200, verbose_name='文章摘要'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_complete_url',
            field=models.CharField(default='#', max_length=200, verbose_name='略缩图原图地址'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_url',
            field=models.CharField(default='#', max_length=200, verbose_name='略缩图地址'),
        ),
    ]
