# Generated by Django 2.2.3 on 2021-02-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210227_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail_complete_url',
            field=models.CharField(default='https://s3.ax1x.com/2021/02/27/69kS8H.png', max_length=200, verbose_name='略缩图原图地址'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_url',
            field=models.CharField(default='https://s3.ax1x.com/2021/02/27/69kS8H.png', max_length=200, verbose_name='略缩图地址'),
        ),
    ]
